name: Build & Push Docker Image + Security Scan

on:
  push:
    branches: [ part1 ]
  pull_request:
    branches: [ part1 ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    name: Docker Build & SÃ©cu Scan

    steps:
      - name: ğŸ“¥ Checkout du code
        uses: actions/checkout@v3

      - name: ğŸ” Connexion Ã  DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ› ï¸ Build de lâ€™image Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:dev-${{ github.sha }} .

      - name: ğŸš€ Push de lâ€™image vers Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-app:dev-${{ github.sha }}

      - name: ğŸ›¡ï¸ Scan de sÃ©curitÃ© avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/mon-app:dev-${{ github.sha }}'
          format: 'table'
          exit-code: '1'  # Fait Ã©chouer le job en cas de vulnÃ©rabilitÃ©s
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
